modLoader="javafml"
loaderVersion="[4,)"
license="GPL-3.0-or-later"
issueTrackerURL="https://github.com/Lovkar-Squid/voyager/issues"

[[mods]]
modId="voyager"
version="0.2.0"
displayName="Voyager"
description='''A new MineColonies profession that explores the End. Build a Departure Point - as a Launchpad with a rocket or as an End Gate - hire a Voyager, and they will leave on expeditions and come back with end stone, purpur, chorus, ender pearls, shulker shells... if they come back. Made by Lovkar & Claude.'''
authors="Lovkar & Claude"
displayURL="https://github.com/Lovkar-Squid/voyager"
logoFile="voyager_logo.png"

[[dependencies.voyager]]
modId="neoforge"
type="required"
versionRange="[21.1,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.voyager]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.voyager]]
modId="minecolonies"
type="required"
versionRange="[1.1.1300,1.2)"
ordering="AFTER"
side="BOTH"

[[dependencies.voyager]]
modId="structurize"
type="required"
versionRange="[1.0.800,)"
ordering="AFTER"
side="BOTH"
